/*
Copyright 2022 Pure Storage Inc
SPDX-License-Identifier: Apache-2.0
*/

// Code generated DO NOT EDIT.
/*
 * Pure Fusion API
 *
 * Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fusion

type StorageEndpointIscsiDiscoveryInterfacePost struct {
	// The IPv4 address for this interface.
	Address string `json:"address"`
	// The IPv4 address of the gateway through which this interface will communicate with the network.
	Gateway                string   `json:"gateway,omitempty"`
	NetworkInterfaceGroups []string `json:"network_interface_groups,omitempty"`
}
