/*
Copyright 2022 Pure Storage Inc
SPDX-License-Identifier: Apache-2.0
*/

// Code generated DO NOT EDIT.
/*
 * Pure Fusion API
 *
 * Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fusion

// PlacementEngine : Policy engine used for determining Placements. If not specified, the default is \"pure1meta\". Pure1 Meta recommendations might take a few minutes to process.
type PlacementEngine string

// List of PlacementEngine
const (
	PURE1META_PlacementEngine  PlacementEngine = "pure1meta"
	HEURISTICS_PlacementEngine PlacementEngine = "heuristics"
)
