/*
Copyright 2022 Pure Storage Inc
SPDX-License-Identifier: Apache-2.0
*/

// Code generated DO NOT EDIT.
/*
 * Pure Fusion API
 *
 * Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fusion

type NetworkInterfaceGroupEthPost struct {
	// The IPv4 prefix for Network Interfaces in this Network Interface Group.
	Prefix string `json:"prefix"`
	// The IPv4 address of the gateway for Network Interfaces in this Network Interface Group.
	Gateway string `json:"gateway,omitempty"`
	// Maximum message transfer unit (packet) size in bytes for the Network Interfaces in this Network Interface Group. MTU setting cannot exceed the MTU of the underlying physical interfaces.
	Mtu int32 `json:"mtu"`
}
