/*
Copyright 2022 Pure Storage Inc
SPDX-License-Identifier: Apache-2.0
*/

// Code generated DO NOT EDIT.
/*
 * Pure Fusion API
 *
 * Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fusion

// (Provider)
type StorageEndpointCbsAzureIscsiPost struct {
	// The Storage Endpoint Collection Identity which belongs to the Azure entities.
	StorageEndpointCollectionIdentity string `json:"storage_endpoint_collection_identity,omitempty"`
	// The Load Balancer id which gives permissions to CBS array appliations to modify the Load Balancer.
	LoadBalancer          string   `json:"load_balancer,omitempty"`
	LoadBalancerAddresses []string `json:"load_balancer_addresses,omitempty"`
}
