/*
Copyright 2022 Pure Storage Inc
SPDX-License-Identifier: Apache-2.0
*/

// Code generated DO NOT EDIT.
/*
 * Pure Fusion API
 *
 * Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fusion

// Additional description about the Placement Group, had it been created. This is only used to make a PlacementRecommendation for a new Placement Group that doesn't already exist.
type SimulatedPlacementPost struct {
	// If Placement Group would have been created, which Availability Zone would it be created in
	AvailabilityZone string `json:"availability_zone"`
	// If Placement Group would have been created, which Region would it be created in
	Region string `json:"region"`
	// If Placement Group would have been created, which Storage Service would it be assigned
	StorageService string `json:"storage_service"`
}
