/*
Copyright 2022 Pure Storage Inc
SPDX-License-Identifier: Apache-2.0
*/

// Code generated DO NOT EDIT.
/*
 * Pure Fusion API
 *
 * Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fusion

// An Ethernet interface on an Array
type NetworkInterfaceEth struct {
	// The IPv4 address associated with this Network Interface.
	Address string `json:"address,omitempty"`
	// The IPv4 address of the gateway through which this Network Interface will communicate with the network.
	Gateway string `json:"gateway,omitempty"`
	// The media access control address associated with this Network Interface.
	MacAddress string `json:"mac_address,omitempty"`
	// The maximum message transfer unit size for this Network Interface (in bytes).
	Mtu int32 `json:"mtu,omitempty"`
	// The VLAN ID for this Network Interface.
	Vlan int32 `json:"vlan,omitempty"`
}
